### ISSUE TITLE
Accessing swapsteem.online (without www. )fails on mobile chrome 

### ISSUE THREAD

**Issue by realrufans** [nirvanaitsolutions/swapsteem#68]
Describe the bug
Site doesnt open without adding www. on mobile browser

To Reproduce
 try accessing swapsteem.online with chrome on mobile

Expected behavior 

 i expected swapsteem.online to be redirected to www.swapsteem.online when accessed on mobile. 
it redirects to https://shortener.secureserver.net/error_404 instead.
 
Screenshots

![ses.png](https://cdn.steemitimages.com/DQmVkFBMTAi5riyANARKyWQTHNb1KvAQG2rnNZrBH18Dpw2/ses.png)

Browser: Google Chrome (Version 71.0.3578.98 
Device: Tecno camon xpro
Operating system: Android 0

**Comment by nirvanaitsolutions** [comment]
I am unable to reproduce on my redmi mi 5

**Comment by realrufans** [comment]
![okayna.gif](https://cdn.steemitimages.com/DQmPqxbJdWnzPzjB4C4oLVorSWTicwcp857LQW6DMxChKmY/okayna.gif)

**Comment by nirvanaitsolutions** [comment]
Although our mobile ui is unresponsive but I can access swapsteem.online without any problem

**Comment by nirvanaitsolutions** [comment]
Which country are you from @realrufans ?

**Comment by realrufans** [comment]
Nigeria

**Comment by nirvanaitsolutions** [comment]
@realrufans, It has been fixed. can you try to reproduce?

**Comment by realrufans** [comment]
it worked fine when tried it on same browser I have been getting the error on.  

But the issue still persists when I tried it with another browser.

**Comment by tobias-g1** [comment]
I was also able to replicate this, I had similar issues when using Go Daddy for my DNS, it might be worth transferring your DNS to Cloudflare as they offer CNAME flattening.

**Comment by nirvanaitsolutions** [comment]
We are ready using cloudflare, will move the domain ownership to cloudflare soon

**Comment by tobias-g1** [comment]
Oh okay, do you have CNAME set up for both www.swapsteem.online and swapsteem.online?

**Comment by nirvanaitsolutions** [comment]
Yes. @tobias-g1

**Comment by nirvanaitsolutions** [comment]
Closing this for not being able to reproduce on latest version.
